### ISSUE TITLE
I added a model, I don't know why there is no physical characteristics

### ISSUE THREAD

**Issue by pxim** [donmccurdy/three-to-cannon#120]
example:https://codesandbox.io/s/relaxed-margulis-ms8z8v?file=/src/Tangent.js:8304-8307

Small balls and squares will penetrate the scene model.
I do not know why it has to be like this.
![image](https://user-images.githubusercontent.com/5111701/233236999-c31185df-5a4d-4a8f-a101-a9f0247b98fe.png)

**Comment by donmccurdy** [comment]
Cannon.js does not provide continuous collision detection – it runs collision checks only during frame updates. As objects become smaller or move faster, they can certainly pass through thin colliders in the simulation. 

I am not a maintainer of Cannon.js, so reaching out on the repository or Poimandres Discord may be a better option here:

- https://github.com/pmndrs/cannon-es
- https://pmnd.rs/discord
