### ISSUE TITLE
"points is not defined" HULL type error

### ISSUE THREAD

**Issue by swift502** [donmccurdy/three-to-cannon#14]
Hi!
I get this error while trying to use the HULL type.

![image](https://user-images.githubusercontent.com/24359130/48660085-56dcc580-ea5c-11e8-8efb-f5881c844cc0.png)

I can't pretty-print the file, and when I looked for ".points" in the error file, but couldn't find anything like that.

My code goes like this:

```js
import { threeToCannon } from 'three-to-cannon';

const object = new THREE.Mesh(new THREE.BoxGeometry(10, 10, 10));
const shape = threeToCannon(object, {type: threeToCannon.Type.HULL});
```

I ran it on THREE r92 and r99 but the error is in both versions. Any idea what I've done wrong?
Thanks.

**Comment by swift502** [comment]
Alright, sorry.

The above is incorrect, Geometry create with the THREE constructors works just fine, it's that the imported gltf or fbx geometry doesn't have the vertices, nor faces attributes... I think that's it.

**Comment by donmccurdy** [comment]
Looks like the error is coming from pathfinding, not this module? The newer version of pathfinding should support BufferGeometry.

**Comment by swift502** [comment]
@donmccurdy It still happens. I'm not sure about when exactly it happens though. I gave up eventually.

I know that by default, the npm module threw this error for me when trying to convert gltf imported meshes with the HULL type.
