### ISSUE TITLE
not getting desired boundaries with simple cube like shapes 

### ISSUE THREAD

**Issue by elkizana** [donmccurdy/three-to-cannon#158]
How to get rid of these extra boundaries 
![cannon](https://github.com/donmccurdy/three-to-cannon/assets/53874333/5758b4a9-341c-4d87-ae46-e8631b0f7a6a)

**Comment by donmccurdy** [comment]
It looks like you might be fitting a bounding box to your mesh. For a closer fit, use the convex hull or mesh types: https://github.com/donmccurdy/three-to-cannon?tab=readme-ov-file#api

**Comment by elkizana** [comment]
result with ` {type: ShapeType.HULL} `  :
![Screenshot from 2024-01-25 18-55-08](https://github.com/donmccurdy/three-to-cannon/assets/53874333/a054a2c9-e863-41ae-be4b-d7a7f93e7abb)

**Comment by donmccurdy** [comment]
@elkizana That's what [convex hulls](https://en.wikipedia.org/wiki/Convex_hull) are — think of it like stretching shrink-wrap around an object. If you need a tight fit around concave objects in Cannon.js, then the "mesh" type is your only option, and there are a bunch of performance and support caveats with that, unfortunately.

Ideally your meshes above could be fit with a collection of 'compound' box-shaped bodies, one box fitted to each box-shaped segment of the mesh... But that's not something this library can automate for you.

**Comment by elkizana** [comment]
@donmccurdy thank you !
Have you looked at https://github.com/lo-th/phy

**Comment by donmccurdy** [comment]
Very cool! I hadn't seen this yet. It supports higher-end WASM-based physics engines like Havok and Rapier, and might have better options for you indeed.

**Comment by elkizana** [comment]
how can it have more detailed collision ?

**Comment by donmccurdy** [comment]
Cannon.js has some significant limitations on collisions with trimesh bodies — discussed in more detail at https://github.com/pmndrs/cannon-es/issues/21. I believe Rapier and Havok have better options for that, but it's always going to be more expensive than colliding with primitive shapes. 

In general though, meshes are just a pile of triangles as far as the runtime can see, so it's difficult for an engine to guess how you want to simulate it for performance vs. detail. Usually a good idea to make that decision for the engine if you can.
