### ISSUE TITLE
why not use ConvexHull from THREE

### ISSUE THREAD

**Issue by arpu** [donmccurdy/three-to-cannon#18]
why not use ConvexHull from THREE ?
https://threejs.org/docs/#examples/en/math/convexhull/ConvexHull

**Comment by donmccurdy** [comment]
Whatever we use would have to be copied into this repository, as my build isn't set up to extract parts of three.js and bundle them. I don't recall why I chose this version, though.

**Comment by arpu** [comment]
i asking for me it looks like with the THREE version it would be possible to use a  ConvexHull from a THREE Object3d   and not only from points

**Comment by donmccurdy** [comment]
I think it supports mesh geometry, not just points? Maybe I'm not sure what you mean. But feel free to update it if something is out of date!
