### ISSUE TITLE
Missing dependency version

### ISSUE THREAD

**Issue by RogueSheep-nl** [donmccurdy/three-to-cannon#2]
When installing (this package directly or aframe-extras), I get a:
_No compatible version found: cannon@'github:donmccurdy/cannon.js#v0.6.2-dev1'_

**Comment by donmccurdy** [comment]
When I clone/install this package I get:

```
three-to-cannon@1.0.5 requires a peer of cannon@github:donmccurdy/cannon.js#v0.6.2-dev1 but none was installed.
```

^which is fine and can be ignored. aframe-extras installs correctly for me..

What version of NPM + Node.js do you have?

**Comment by RogueSheep-nl** [comment]
Thanks! Seems I was in dire need of an update, my version was 1.4.3 :-/
After updating the install runs fine!
