### ISSUE TITLE
THREE is not defined

### ISSUE THREAD

**Issue by benolayinka** [donmccurdy/three-to-cannon#21]
When I import the package as an ES6 module
`import { threeToCannon } from 'three-to-cannon';`

I get a `THREE is not defined` error

In [source](https://github.com/donmccurdy/three-to-cannon/blob/master/lib/THREE.quickhull.js) THREE is never imported - how is the library supposed to be linked?

**Comment by donmccurdy** [comment]
It's expected to be a global at the moment. I'm open to changing this, but haven't had time to work on it lately. There's some discussion of a proposed approach in https://github.com/donmccurdy/three-to-cannon/pull/15.

**Comment by donmccurdy** [comment]
Here's an attempt, although it's currently blocked: https://github.com/donmccurdy/three-to-cannon/pull/22.

**Comment by donmccurdy** [comment]
Fixed in 3.0.0 — `three` and `cannon-es` are peer dependencies, and should be handled by your bundler (or added as globals if necessary).

**Comment by benolayinka** [comment]
amazing. you're the man!
