### ISSUE TITLE
Geometry → BufferGeometry

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-to-cannon#31]
The Geometry class is being removed from three.js in r125, and will only be available as an import from `examples/jsm/deprecated`. BufferGeometry has long been the preferred representation, so we should update this tool to rely only on BufferGeometry. If necessary we can continue to support Geometry as input, calling `toBufferGeometry()` on it.

Details: https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401

**Comment by Qouagga** [comment]
I try to use  three-to-cannon to convert my gltf blender model three mesh to a cannonJs body. But this library use Geometry not BufferGeometry. Anybody work on this update ?
I am  beginner dev, I am not sure if I can help you. But I can try.
