### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by w99910** [donmccurdy/three-to-cannon#33]
Can't install three-to-cannon for three 0.124 
![Screenshot (156)](https://user-images.githubusercontent.com/65523475/106145078-7ecf2400-61a3-11eb-83d2-29459db20d31.png)

**Comment by w99910** [comment]
Sorry for my dumb . I downgrade the three js version. and solve.

**Comment by donmccurdy** [comment]
Hm, the version requirement should probably not be that tight. I'll loosen it in the next release, see https://github.com/donmccurdy/three-to-cannon/commit/5a5e36d55318ff5e47eecd3520b86cb83bc125ad.
