### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by oveddan** [donmccurdy/three-to-cannon#37]
Thanks for this very useful library!  Would it be possible to export typescript definitions?  Thank you!

**Comment by donmccurdy** [comment]
I'd be open to the idea of converting this library to TypeScript — still using Microbundle, and ideally with the same build configuration as https://github.com/donmccurdy/KTX-Parse — but I don't have bandwidth to work on that in the near future. PRs would certainly be welcome. I tried to start in https://github.com/donmccurdy/three-to-cannon/pull/35 but the PR got stalled with messy details in the Geometry vs. BufferGeometry types, described in https://github.com/donmccurdy/three-to-cannon/issues/31.

Unfortunately I've had bad experiences with trying to maintain typescript definitions alongside a JavaScript library. The TS tooling for verifying correctness of those files is not adequate. So I am not able to consider taking that approach.
