### ISSUE TITLE
The createConvexPolyhedron function returns cannon shape without faces.

### ISSUE THREAD

**Issue by TheOsrd** [donmccurdy/three-to-cannon#39]
The shape returned has both vertices and facenormals but not the faces, and with the help of CannonDebugRenderer I can confirm that the shape itself is correct. However, whenever a collision occurs between the player(A cannon box) and the convexPolyhedron, an error occurs: **"Cannot read property 'length' of undefined at ConvexPolyhedron.clipAgainstHull (cannon-es.js:2347)"**. After looking at the cannon-es code I can see that it is trying to access the length of the faces array, which is undefined!

I've tried many different solutions to this. Using the ConvexHull method I can get faces and vertices but they are of THREE.Face and THREE.Vector3 respectively and CANNON wants simple arrays of which vertices to use. Further, I've tried to convert the vertices to Vec3, which worked, but figuring out how to create the face arrays was very tricky. In the end it gave me a bunch of errors since the vertices were not ordered correctly, CCW right hand rule and all that. 

Either way there might be a bug with the createConvexPolyhedron function or im simply not using it correctly. Would be glad to get some feedback!

**Comment by TheOsrd** [comment]
I made some progress by altering the code in index.ts by adding a faces array(Consisting of arrays the way Cannon wants it). The CannonDebugRenderer still shows the correct shapes and I get no errors while colliding. However, not all faces are collidable. It seems to be less than half of all faces that have a physical representation. The ones that do collide are correct. I've seen a similar problem elsewhere but can't seem to find it. I can't really wrap my head around what's going on.

**Comment by donmccurdy** [comment]
Could you share your current changes to the code, and perhaps the input geometry?

**Comment by donmccurdy** [comment]
Also, are you installing this project from the latest GitHub repo or from NPM? A lot of refactoring has happened on GitHub since the last version (v3) was published to NPM, and these changes are not necessarily stable yet.

**Comment by TheOsrd** [comment]
I installed it from the latest GitHub repo since I couldn't get the NPM version to work for some reason, I might give that a try again to see if things clear up. I also noticed the NPM one relied somewhat on the deprecated THREE.Geometry class. Anyway here are the changes I made to index.ts (note I converted the file from TS to JS but none of the logic should be changed by that):

`// Compute the 3D convex hull.
    var hull = new ConvexHull_js_1.ConvexHull().setFromObject(new three_1.Mesh(geometry));
    var faces = hull.faces;
    var cannonFaces = [];
    var vertices = [];
    var normals = [];
    for (var i = 0; i < faces.length; i++) {
        var face = faces[i];
        var cannonFace = []
        var edge = face.edge;
        do {
            var point = edge.head().point;
            var vec3 = new cannon_es_1.Vec3(point.x, point.y, point.z)
            vertices.push(vec3);
            normals.push(new cannon_es_1.Vec3(face.normal.x, face.normal.y, face.normal.z));
            cannonFace.push(vertices.indexOf(vec3))
            edge = edge.next;
        } while (edge !== face.edge);
        cannonFaces.push(cannonFace)
    }
    var shape = new cannon_es_1.ConvexPolyhedron({ vertices: vertices, normals: normals, faces: cannonFaces });
    return { shape: shape };`

This is in the createConvexPolyhedron function. I added the cannonFaces array as the faces array. Each face is then an array consisting of the index of it's three vertices in relation to the vertices array (as I understood from the CANNON documentation). I've tried different geometries(both imported and from pure Three geometries) but they yield similar results.

**Comment by TheOsrd** [comment]
The method I used might be completely off but I find it strange how some of the faces are correct and other just seem to not exist.

**Comment by donmccurdy** [comment]
If you'd rather try the latest stable version (which is also what's on NPM) you can find it on GitHub here:

https://github.com/donmccurdy/three-to-cannon/tree/v3.1.0

But, as you mention it relies heavily on THREE.Geometry, and refactoring to avoid that required a lot of changes. It may be because of those changes that the current `main` branch on GitHub is not working correctly. 

> I've tried different geometries(both imported and from pure Three geometries) but they yield similar results.

Hm that's surprising, do any of the pure three.js geometries give this same problem? I'm confused that cannon.js even wants the face normals; it seems like physics simulation would work without those, but I'm not sure of the cannon.js internals. If we think it's a bug in the `cannon-es` repository we could report it there too, they're pretty active.

**Comment by TheOsrd** [comment]
> hm that's surprising, do any of the pure three.js geometries give this same problem?

I tried a couple different ones but they all give the same error as the one mentioned in the first post. After the changes I made, adding the faces array and not providing the normals in the ConvexPolyhedron constructor, they seem to work as intended (even without any warings about inward faces and that). As you said this could potentially be a cannon-es bug but I haven't dug into that code enough either. As for now I'll try and work out the few inward faces and hopefully stick with this solution.

**Comment by donmccurdy** [comment]
Ok! Sounds like https://github.com/donmccurdy/three-to-cannon/pull/40 fix this then?

**Comment by donmccurdy** [comment]
Oops sorry, I'd meant to say that #40 _will_ fix this issue. Would be great if you're able to confirm that works for the cases you are testing?

**Comment by donmccurdy** [comment]
Ok, thanks! Would be curious what you find out, I'll try to get a new version of three-to-cannon published fairly soon.
