### ISSUE TITLE
Use with common js (no node.js)?

### ISSUE THREAD

**Issue by NabeelUppel** [donmccurdy/three-to-cannon#43]
How do I use this library if I do not want to use node.js?
I'm using Three.js  and cannon-es as modules from my local directory

Sorry, I know this is the wrong place to ask this.

**Comment by donmccurdy** [comment]
This library is published to NPM, and there are a number of ways to get a package from NPM. Using the `npm` client (which comes with Node.js) the best way, but CDNs are also an option to grab the relevant files:

https://unpkg.com/three-to-cannon@4.0.2/dist/three-to-cannon.js

^in this case you will need to edit the file yourself to resolve dependencies, which npm or a bundler would otherwise handle. Something like this, depending on how you are loading those dependencies and exposing them as global variables:

```
// before:
var e=require("cannon-es"),t=require("three") ...

// after:
var e=CANNON,t=THREE ...
```

**Comment by NabeelUppel** [comment]
I'm probably doing something but it does not seem to work. I've added the file to my directory and imported it but it does not seem to work.
My source file begins with
```import * as THREE from './resources/threejs/r128/build/three.module.js';
import {OrbitControls} from './resources/threejs/r128/examples/jsm/controls/OrbitControls.js';
import {FBXLoader} from './resources/threejs/r128/examples/jsm/loaders/FBXLoader.js';
import * as CANNON from './resources/cannon-es/dist/cannon-es.js'
import * as threeToCannon from "./resources/three-to-cannon/three-to-cannon.js";
```
And changed the lines in three-to-cannon.js
Would I also need the other files in the repo such convexhull.js?

**Comment by donmccurdy** [comment]
Other than the external dependencies on `cannon-es` and `three`, everything else is (or should be!) bundled into a single file when it's published. Do you see any particular error when it doesn't work?

If you're using ES Modules then you may want the ES Module version of three-to-cannon, which would require slightly different edits to get the right paths to cannon-es and three...

https://unpkg.com/three-to-cannon@4.0.2/dist/three-to-cannon.modern.js?module

Hopefully that will show clear errors if the URL it imports is not the right one.

I really like https://www.snowpack.dev/, IMO it makes local development with ES Modules much more convenient.

**Comment by NabeelUppel** [comment]
Ah that was the issue, I used the ES Module version and imported cannon and three using the local scripts and it worked like a charm. 
Thank you! 
I'll definitely look in snowpack it looks quite interesting.
One more question before you clsoe this,  how do scale the shape/body?

**Comment by donmccurdy** [comment]
When you add the returned Shape to a cannon.js body, you can set an offset and rotation for it, but unfortunately I don't think cannon.js provides a way to scale the shape:

https://pmndrs.github.io/cannon-es/docs/classes/body.html#addshape

Might be a good question for the cannon-es folks, or you can always scale the three.js object before passing it to three-to-cannon.
