### ISSUE TITLE
README: dead link

### ISSUE THREAD

**Issue by obfuscatedgenerated** [donmccurdy/three-to-cannon#66]
The link to CANNON.Shape docs leads to https://pmndrs.github.io/cannon-es/docs/classes/shape.html which has a 404.

![image](https://user-images.githubusercontent.com/75035364/152052491-906a310d-ac8c-4d72-9328-cd170d6f613f.png)

**Comment by obfuscatedgenerated** [comment]
I found the issue: the S in Shape.html needs to be a capital.

https://pmndrs.github.io/cannon-es/docs/classes/Shape.html

**Comment by donmccurdy** [comment]
Sounds like https://github.com/TypeStrong/typedoc/issues/1633 broke this link. Fixed, thanks!

**Comment by obfuscatedgenerated** [comment]
It still seems to be the wrong path, despite your commit (?)

**Comment by obfuscatedgenerated** [comment]
Ah wait, you changed one of the link but not the second lower down. The first works fine now.
