### ISSUE TITLE
Uncaught TypeError: shape.calculateWorldAABB is not a function

### ISSUE THREAD

**Issue by MarcJamesIO** [donmccurdy/three-to-cannon#71]
The project is throwing this error when attempting to use:

cannon-es.js:3679 Uncaught TypeError: shape.calculateWorldAABB is not a function
at Body.updateAABB (cannon-es.js:3679:13)
at Body.updateMassProperties (cannon-es.js:3856:10)
at Body.addShape (cannon-es.js:3602:10)
at new Body (cannon-es.js:3455:12)
at main.js?t=1649830614683:225:20

Here is the code: 

`let custom = await loadFile(".glb", "./models/custom-``collider.glb");`
`const customShape = threeToCannon(custom.scene);`
`scene.add(custom.scene);`

`const customBody = new CANNON.Body({`
  `mass: 1,`
 ` position: new CANNON.Vec3(0, 0, 0),`
  `shape: customShape,`
 ` material: defaultMaterial,`
`});`

`customBody.position.copy(custom.position);`
`world.addBody(customBody);`

I've attempted a few things to no avail!

**Comment by donmccurdy** [comment]
Hi! The important parts of this error are probably:

1. what `custom.scene` contain? does it have at least one mesh with some geometry?
2. what is `threeToCannon` returning? a `CANNON.Shape`? null? 

You can probably step through the code in a debugger but I don't have a way to reproduce this issue or access any of that information, so you may need to dig into this error more or provide information allowing me to reproduce this.

**Comment by MarcJamesIO** [comment]
Sure, here's the mesh I'm importing:

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/12461155/163193164-e1241a5c-d7f4-4888-a20e-63a99cdd1c16.png">

It's a standard Group, with a child as a Mesh (same error occurs if I try three-to-cannon with just the mesh)

<img width="828" alt="image" src="https://user-images.githubusercontent.com/12461155/163193717-48b9827c-0694-401c-a72b-053122b7d10b.png">

ThreeToCannon is returning:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/12461155/163193915-cdde0673-d7a8-43b2-82a1-3832a40333f7.png">

**Comment by donmccurdy** [comment]
Oh I see. The result of the `threeToCannon` is not just a CANNON.Shape — it may also provide an offset and/or quaternion needed to correctly position the shape.

```js
// instead of this ...
const customShape = threeToCannon(custom.scene);

// ... do this ...
const { shape, offset } = threeToCannon(custom.scene);

// ... or this:
const result = threeToCannon(custom.scene);
const shape = result.shape;
```

**Comment by MarcJamesIO** [comment]
Ah ok, thanks.

That kind of works: 

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/12461155/163197166-86f1fa52-07f9-4d00-9221-530ded2978b9.png">

**Comment by donmccurdy** [comment]
The "automatic" result will usually be a bounding box, unless your model contains obvious primitives like THREE.SphereGeometry or THREE.CylinderGeometry. You can also use a convex hull to more closely fit the shape (see README.md) but those have some performance and collision detection constraints unless cannon.js has improved in that area.

**Comment by MarcJamesIO** [comment]
That's great to know, thanks so much for your time! Here's the final result:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/12461155/163199319-b9751eac-ff3f-4ed9-a78e-ffe266a8de76.png">
