### ISSUE TITLE
getVertices() has a bug that causes trimesh issue

### ISSUE THREAD

**Issue by AndyMGar** [donmccurdy/three-to-cannon#72]
The getVertices function is incorrectly accessing the geometry vertex positions.

Current function
      export function getVertices (geometry: BufferGeometry): Float32Array {
	      const position = geometry.attributes.position;
	      const vertices = new Float32Array(position.count * 3);
	      for (let i = 0; i < position.count; i += 3) {
		      vertices[i] = position.getX(i);
		      vertices[i + 1] = position.getY(i);
		      vertices[i + 2] = position.getZ(i);
	      }
	      return vertices;
      }

Easily fixed as follows:
      export function getVertices (geometry: BufferGeometry): Float32Array {
         const position = geometry.attributes.position;
         const vertices = new Float32Array(position.count * 3);
         for (let i = 0; i < position.count; i++) {
              vertices[i*3] = position.getX(i);
              vertices[i*3 + 1] = position.getY(i);
              vertices[i*3 + 2] = position.getZ(i);
         }
         return vertices;
      }

**Comment by AndyMGar** [comment]
Another issue is that the cannon-es trimesh indices parameter is calculated from the vertices list using
	const indices = Object.keys(vertices).map(Number);
This results in a array of integers running from 0 to n, where n is the number of vertices - 1. But it needs to be a index of the vertices of each triangle, which can easily be taken directly from the three.js MESH.geometry.index.

**Comment by donmccurdy** [comment]
Thank you! The original issue is fixed in https://github.com/donmccurdy/three-to-cannon/commit/482b41973d291792f3ff688f3def322b2019035d, the latter issue was fixed a while back.
